version: '3'
services:
  flask:
    build: .
    ports:
      - "80:80"
      - "8000:5000"
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    ports:
      - "8080:80"
    volumes:
      - ./nextcloud:/var/www/html
    restart: unless-stopped

